- name: show rewturn value of command module
  hosts: vagrant1
  become: True
  tasks:
      - name: capture output of id command
        command: id -un
        register: login
      - debug: msg="Logged in as user {{ login.stdout }}"
